docs: Add question answering over a website to web scraping
apify/langchain pull request #6
Opened 2023-09-14 14:17 UTC by jirimoravcik

2023-09-14 14:59 UTC, davidjohnbarton requested changes

2023-09-14 14:59 UTC, davidjohnbarton commented on docs/extras/use_cases/web_scraping.ipynb
> +    "If we want to answer questions over a specific website, you can use Apify's [Website Content Crawler](https://apify.com/apify/website-content-crawler) Actor, which can deeply crawl websites such
```suggestion
    "To answer questions about a specific website, you can use Apify's [Website Content Crawler](https://apify.com/apify/website-content-crawler) Actor, which can deeply crawl websites such as documentation, knowledge bases, help centers, or blogs,\n",
```

2023-09-14 14:59 UTC, davidjohnbarton commented on docs/extras/use_cases/web_scraping.ipynb
> +    "In the example below, we will deeply crawl the Python documentation of LangChain's Chat LLM models and answer a question over it.\n",
```suggestion
    "In the example below, we will deeply crawl the Python documentation of LangChain's Chat LLM models and answer a question about it.\n",
```

2023-09-14 14:59 UTC, davidjohnbarton commented on docs/extras/use_cases/web_scraping.ipynb
> +    "In the example below, we will deeply crawl the Python documentation of LangChain's Chat LLM models and answer a question over it.\n",
```suggestion
    "In the example below, we will deeply crawl the Python documentation of LangChain's Chat LLM models and answer a question about it.\n",
```

2023-09-14 19:52 UTC, jirimoravcik commented
@davidjohnbarton So I'm guessing that the title should be changed from "Question answering over a website" to "Question answering about a website", right?

2023-09-14 21:42 UTC, davidjohnbarton commented
> @davidjohnbarton So I'm guessing that the title should be changed from "Question answering over a website" to "Question answering about a website", right?

@jirimoravcik I'm not sure about this. My change to "about" makes sense to me, but I'm wondering now whether the formulation "question answering over" is some standard phrase I'm not aware of? I don't want to dumb this copy down. Let's discuss on Slack.

2023-09-15 08:22 UTC, davidjohnbarton approved these changes

2023-09-15 10:34 UTC, merged